### ISSUE TITLE
SparseMeanRevertingOracle's Ornstein-Uhlenbeck step has inncorect scale/standard deviation

### ISSUE THREAD

**Issue by ajoseqms** [jpmorganchase/abides-jpmc-public#10]
From [compute_fundamental_at_timestamp](https://github.com/jpmorganchase/abides-jpmc-public/blob/b2a24e4dd8ba2f437e3a9b0984e3460e7ca7dde1/abides-markets/abides_markets/oracles/sparse_mean_reverting_oracle.py#L103)
```
        mu = s["r_bar"]
        gamma = s["kappa"]
        theta = s["fund_vol"]

        # The OU process is able to skip any amount of time and sample the next desired value
        # from the appropriate distribution of possible values.
        v = s["random_state"].normal(
            loc=mu + (pv - mu) * (exp(-gamma * d)),
            scale=((theta) / (2 * gamma)) * (1 - exp(-2 * gamma * d)),
        )
```
[np.RandomState.normal](https://numpy.org/doc/1.22/reference/random/generated/numpy.random.RandomState.normal.html)'s scale argument should be the standard deviation of the OU process, but the variance is passed instead.

The variance for this time step can be verified here https://planetmath.org/ornsteinuhlenbeckprocess 
or here
https://en.wikipedia.org/wiki/Ornstein%E2%80%93Uhlenbeck_process
with cov(x_t, x_t)

Adjusting to `scale=np.sqrt(((theta) / (2 * gamma)) * (1 - exp(-2 * gamma * d)))`
will at least make the mean reversion consistent with the variance of this step, but I also propose making a symbol change from theta to theta**2 as well for consistency.

The theta parameter is labelled as the "fundamental volatility" of the Brownian motion component of the SDE, but it is being used as the variance of the component following this pull request in the original repository: https://github.com/abides-sim/abides/pull/18

**Comment by Andrea94c** [comment]
Thanks a lot for your contribution,  we are fixing the bug you spotted as part of the next release.

We already created PR #12 to isolate the specific issue you have spotted. Thanks!
