### ISSUE TITLE
rmsc03 does not seem to work

### ISSUE THREAD

**Issue by fipelle** [jpmorganchase/abides-jpmc-public#7]
I have installed ABIDES following the description in the readme file. While rmsc04 works fine, I am having troubles with rmsc03. As soon as I try to import it, I get the following error message:
```python
>>> from abides_markets.configs import rmsc03
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/abides_markets-0.0.0-py3.9.egg/abides_markets/configs/rmsc03.py", line 11, in <module>
ImportError: cannot import name 'POVExecutionAgent' from 'abides_markets.agents' (/usr/local/lib/python3.9/site-packages/abides_markets-0.0.0-py3.9.egg/abides_markets/agents/__init__.py)
```

Have you ever encountered this error before?

**Comment by HaibeiZhu** [comment]
> I have installed ABIDES following the description in the readme file. While rmsc04 works fine, I am having troubles with rmsc03. As soon as I try to import it, I get the following error message:
> 
> ```python
> >>> from abides_markets.configs import rmsc03
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "<frozen zipimport>", line 259, in load_module
>   File "/usr/local/lib/python3.9/site-packages/abides_markets-0.0.0-py3.9.egg/abides_markets/configs/rmsc03.py", line 11, in <module>
> ImportError: cannot import name 'POVExecutionAgent' from 'abides_markets.agents' (/usr/local/lib/python3.9/site-packages/abides_markets-0.0.0-py3.9.egg/abides_markets/agents/__init__.py)
> ```
> 
> Have you ever encountered this error before?


Hi @fipelle,
Thanks for posting this issue. Which branch were you running?
If you were on the main branch, the issue was caused by the missing module of "POVExecutionAgent" in "abides_markets.agents". The "POVExecutionAgent" module is still in the development branch and hasn't been pushed to the main branch. So, please use the "rmsc04" configuration, and feel free to modify the number of different agents.

**Comment by fipelle** [comment]
Thank you!

**Comment by EthanChoukroun** [comment]
Hi, I am encountering the following error:

`TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.`

This code comes from the following line in the policyRL() class:
`self.trainer.restore(best_checkpoint)`

I believe there is a problem on the checkpoints fetched by the function:
`best_checkpoint = analysis.get_best_checkpoint(trial = best_trial_path, mode='max')`

Does anyone know how to solve this?
